### ISSUE TITLE
typo in default:stone_with_messe

### ISSUE THREAD

**Issue by scr267** [Ezhh/other_worlds#5]
@Ezhh Hi :)

I'm wondering if https://github.com/Ezhh/other_worlds/blob/0d9c464698a5bf26f08e8e1a5484bc50cd733545/space_asteroids.lua#L20 is a typo:

```
		c_meseore = minetest.get_content_id("default:stone_with_messe"),
```
should be:
```
		c_meseore = minetest.get_content_id("default:stone_with_mese"),
```
?

I think!?

Thanks! :)

**Comment by SmallJoker** [comment]
Already reported: #4
If I had push access to this repo, I'd fix this.. but well, Ezhh is currently taking a while off.

**Comment by scr267** [comment]
@SmallJoker oh sorry didn't see it... in that case I'll close this issue.   - thanks! :)
